# Generated by Django 4.2.13 on 2024-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminPortal", "0003_alter_shape_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shape",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
