# Generated by Django 4.2.13 on 2024-06-24 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminPortal", "0004_alter_shape_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shape",
        ),
    ]
