# Generated by Django 4.2.13 on 2024-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("Circle", "Circle"),
                            ("Square", "Square"),
                            ("Rectangle", "Rectangle"),
                            ("Triangle", "Triangle"),
                            ("Pentagon", "Pentagon"),
                            ("Hexagon", "Hexagon"),
                            ("Heptagon", "Heptagon"),
                            ("Octagon", "Octagon"),
                            ("Nonagon", "Nonagon"),
                            ("Decagon", "Decagon"),
                            ("Ellipse", "Ellipse"),
                            ("Parallelogram", "Parallelogram"),
                            ("Trapezoid", "Trapezoid"),
                            ("Rhombus", "Rhombus"),
                            ("Star", "Star"),
                            ("Heart", "Heart"),
                            ("Crescent", "Crescent"),
                            ("Arrow", "Arrow"),
                            ("Diamond", "Diamond"),
                            ("Cross", "Cross"),
                            ("Sphere", "Sphere"),
                            ("Cube", "Cube"),
                            ("Cylinder", "Cylinder"),
                            ("Cone", "Cone"),
                            ("Pyramid", "Pyramid"),
                            ("Torus", "Torus"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Red", "Red"),
                            ("Green", "Green"),
                            ("Blue", "Blue"),
                            ("Yellow", "Yellow"),
                            ("Orange", "Orange"),
                            ("Purple", "Purple"),
                            ("Pink", "Pink"),
                            ("Brown", "Brown"),
                            ("Black", "Black"),
                            ("White", "White"),
                            ("Gray", "Gray"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                        ],
                        max_length=255,
                    ),
                ),
                ("shape_image", models.ImageField(upload_to="images/")),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
